{
  "comment": "Exported from https://atlas.bot",
  "formatVersion": 2,
  "exportedAt": "2025-09-08T12:14:56.436Z",
  "actions": [
    {
      "trigger": {
        "__typename": "GuildActionTriggerGuildBoostAdd",
        "channelId": "750785497017614456",
        "type": "GuildBoostAdd"
      },
      "disabled": false,
      "name": "BoostAdd",
      "content": "//// Action created by azgoodaz\r\n//// Thanks Boosters for boosting server in #boosters (boosters only channel)\r\n\r\nThank you {user.mention} for boosting the server! You now have access to this channel. Please see pins for more information.",
      "cooldownSeconds": 0,
      "cooldownType": "User",
      "restriction": null,
      "flags": "0"
    }
  ]
}