{
  "comment": "Exported from https://atlas.bot",
  "formatVersion": 2,
  "exportedAt": "2025-09-08T12:14:54.354Z",
  "actions": [
    {
      "trigger": {
        "__typename": "GuildActionTriggerGuildBoostRemove",
        "channelId": "750785497017614456",
        "type": "GuildBoostRemove"
      },
      "disabled": false,
      "name": "BoostRemove",
      "content": "//// Action created by azgoodaz\r\n//// Informs the channel in #boosters (boosters only channel) that user stopped boosting.\r\n\r\n{user.mention} has removed their boost.",
      "cooldownSeconds": 0,
      "cooldownType": "User",
      "restriction": null,
      "flags": "0"
    }
  ]
}